# Generated by Django 5.0 on 2024-02-27 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8c75d519-66e0-4c40-a3ae-375b85f71027'), editable=False, primary_key=True, serialize=False),
        ),
    ]
