# Generated by Django 5.0.2 on 2024-03-04 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ebe957d2-cfc7-4790-bb43-309454f57008'), editable=False, primary_key=True, serialize=False),
        ),
    ]
