# Generated by Django 5.0 on 2024-03-14 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b321f704-4e89-40ea-b152-ddcda911d9c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
