# Generated by Django 5.0 on 2024-03-28 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cc5b6245-2841-40d5-b353-0fbe13dc5207'), editable=False, primary_key=True, serialize=False),
        ),
    ]
