# Generated by Django 5.0 on 2024-03-28 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('76e3a41e-c4f9-42ec-bf39-60fe4df7ebec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
